### ISSUE TITLE
Is it possible to add support for a 2nd Street Address line?

### ISSUE THREAD

**Issue by skwaugh** [riccardoklinger/placekey#14]
I am trying to assign placekeys to condominium units - all units in a building share a Street address, with the only distinction being the second line (i.e. Unit 1805).

Is it possible to add support for this?  Thanks for building this...very exciting.

**Comment by skwaugh** [comment]
nvm.  I see that I can concat my 1st and 2nd address lines.  thanks!

**Comment by riccardoklinger** [comment]
This is exactly how this should work. create a model with "merge of attributes" as a preprocessing step and then run the processing step on this result! 
thanks for reporting this issue!
